Version of pacstrap that doesn't require root
This version of pacstrap creates Arch chroot
filesystem with required set of packages.
Chroot filesystem can be created in any directory,
which is writable by user, who calls the script.
Unlike original pacstrap, this script doesn't copy
host pacman keyring to chroot directory because, in
general case, usual user doesn't have read permissions
for pacman private keys directory.

diff --git a/pacstrap-noroot.in b/pacstrap-noroot.in
--- a/pacstrap-noroot.in
+++ b/pacstrap-noroot.in
@@ -2,7 +2,7 @@
 
 #
 # Assumptions:
-#  1) User has partitioned, formatted, and mounted partitions on /mnt
+#  1) User created folder for chroot with write permissions
 #  2) Network is functional
 #  3) Arguments passed to the script are valid pacman targets
 #  4) A valid mirror appears in /etc/pacman.d/mirrorlist
@@ -13,7 +13,6 @@ shopt -s extglob
 m4_include(common)
 
 hostcache=0
-copykeyring=1
 copymirrorlist=1
 pacmode=-Sy
 
@@ -24,7 +23,6 @@ usage: ${0##*/} [options] root [packages...]
   Options:
     -C <config>    Use an alternate config file for pacman
     -c             Use the package cache on the host, rather than the target
-    -G             Avoid copying the host's pacman keyring to the target
     -i             Prompt for package confirmation when needed (run interactively)
     -M             Avoid copying the host's mirrorlist to the target
     -U             Use pacman -U to install packages
@@ -42,8 +40,6 @@ if [[ -z $1 || $1 = @(-h|--help) ]]; then
   exit $(( $# ? 0 : 1 ))
 fi
 
-(( EUID == 0 )) || die 'This script must be run with root privileges'
-
 while getopts ':C:cdGiMU' flag; do
   case $flag in
     C)
@@ -57,9 +53,6 @@ while getopts ':C:cdGiMU' flag; do
       ;;
     i)
       interactive=1
-      ;;
-    G)
-      copykeyring=0
       ;;
     M)
       copymirrorlist=0
@@ -101,20 +94,22 @@ mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{de
 mkdir -m 1777 -p "$newroot"/tmp
 mkdir -m 0555 -p "$newroot"/{sys,proc}
 
-# mount API filesystems
-chroot_setup "$newroot" || die "failed to setup chroot %s" "$newroot"
-
-if (( copykeyring )); then
-  # if there's a keyring on the host, copy it into the new root, unless it exists already
-  if [[ -d /etc/pacman.d/gnupg && ! -d $newroot/etc/pacman.d/gnupg ]]; then
-    cp -a /etc/pacman.d/gnupg "$newroot/etc/pacman.d/"
-  fi
-fi
+fakechroot -- fakeroot -- pacman-key --gpgdir ${newroot}/etc/pacman.d/gnupg --init
+fakechroot -- fakeroot -- pacman-key --gpgdir ${newroot}/etc/pacman.d/gnupg --populate
 
 msg 'Installing packages to %s' "$newroot"
-if ! unshare --fork --pid pacman -r "$newroot" $pacmode "${pacman_args[@]}"; then
+
+# /dev/null is required for installation of certain packages like gnupg
+ln -s /dev/null "$newroot/dev/null"
+
+if ! fakechroot -- fakeroot -- pacman -r "$newroot" $pacmode "${pacman_args[@]}" fakechroot fakeroot ; then
   die 'Failed to install packages to new root'
 fi
+
+# Due to static build of ldconfig it fails when called by pacman under fakeroot, so we need to run it inside sandbox
+fakechroot -- fakeroot -- chroot "$newroot" ldconfig
+
+rm "$newroot/dev/null"
 
 if (( copymirrorlist )); then
   # install the host's mirrorlist onto the new root
